# ANSI colors for fg:NUMBER
# https://i.stack.imgur.com/KTSQa.png

# Don't print a new line at the start of the prompt
add_newline = true

format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$golang\
$elixir\
$helm\
$terraform\
$memory_usage\
$gcloud\
$cmd_duration\
$line_break\
$time\
$status\
$character"""

[time]
disabled = false
format = "[$time]($style) "
style = "#888888"
use_12hr = true

[gcloud]
format = '[$symbol (\($project\))](dimmed green) '

[kubernetes]
format = 'on [☸ $context \($namespace\)](fg:031) '
disabled = false

[kubernetes.context_aliases]
"gke_production-195315_us-east1_prod-us-east1-summer-1" = "prod-us-east1-summer-1"
"gke_staging-205121_us-east1_staging-us-east1-spring-1" = "staging-us-east1-summer-1"
