# ANSI colors for fg:NUMBER
# https://i.stack.imgur.com/KTSQa.png

# Don't print a new line at the start of the prompt
add_newline = true

format = """
$username\
$hostname\
$shlvl\
$gcloud\
$kubernetes\
$directory\
$git_branch\
$git_metrics\
$git_commit\
$git_state\
$git_status\
$golang\
$elixir\
$helm\
$terraform\
$memory_usage\
$cmd_duration\
$line_break\
$time\
$status\
$character"""

[time]
disabled = false
format = "[$time]($style) "
style = "#888888"
use_12hr = true

[gcloud]
format = '[$symbol (\($project\))](green) '

[kubernetes]
format = '[$symbol$context( \($namespace\))]($style) ➠ '
style = "blue"
disabled = false

[kubernetes.context_aliases]
"gke_production-195315_us-east1_prod-us-east1-tier-1" = "prod-tier-1"
"gke_production-195315_us-east1_prod-us-east1-summer-1" = "prod-summer"
"gke_staging-205121_us-east1_staging-us-east1-cse" = "staging cse"
"gke_staging-205121_us-east1_staging-soar-us-east1" = "staging soar"
"gke_staging-205121_us-east1_staging-us-east1-brands" = "staging brands"
"gke_staging-205121_us-east1_staging-so-us-east1-spring-1" = "staging so"
"gke_staging-205121_us-east1_staging-us-east1-spring-1" = "staging summer"

[golang]
symbol = " "
style = "cyan"

[ruby]
symbol = " "
style = "red"

[git_branch]
symbol = " "
style = "white"

[directory]
style = "yellow"
